//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cochesEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public int id { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> numPuertas { get; set; }
        public string color { get; set; }
        public Nullable<int> kilometros { get; set; }
        public string tipoVehiculo { get; set; }
        public Nullable<int> garantia { get; set; }
        public bool stock { get; set; }
        public string fotografia { get; set; }
    }
}
